  FrontendCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: WorkshopsFrontendApp
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactsBucket
      Stages:
        - Name: Source
          Actions:
            - Name: SourceCode
              Region: eu-central-1
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: '1'
                Provider: GitHub
              Configuration:
                Owner: wojciech-dabrowski
                Repo: aws-ci-cd
                Branch: master
                OAuthToken: !Ref GithubToken
                PollForSourceChanges: true
              OutputArtifacts:
                - Name: SourceCode
              RunOrder: 1
            - Name: TemplateConfig
              Region: eu-central-1
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: S3
                Version: '1'
              Configuration:
                S3Bucket: !Ref ArtifactsBucket
                S3ObjectKey: WorkshopsFrontendApp/app-config.zip
              OutputArtifacts:
                - Name: TemplateConfig
              RunOrder: 1
        - Name: DeployTemplate
          Actions:
            - Name: DeployTemplate
              Region: eu-central-1
              InputArtifacts:
                - Name: SourceCode
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_IAM
                RoleArn: !GetAtt CodePipelineRole.Arn
                StackName: cloud-workshops-static-website
                TemplatePath: SourceCode::frontend/static-website.yaml
        - Name: Build
          Actions:
            - Name: BuildApp
              Region: eu-central-1
              InputArtifacts:
                - Name: SourceCode
                - Name: TemplateConfig
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              Configuration:
                ProjectName: BuildWorkshopsFrontendApp
                PrimarySource: SourceCode
              OutputArtifacts:
                - Name: CodePackage
        - Name: Test
          Actions:
            - Name: TestApp
              Region: eu-central-1
              InputArtifacts:
                - Name: SourceCode
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              Configuration:
                ProjectName: TestWorkshopsFrontendApp


  BuildFrontendProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: BuildWorkshopsFrontendApp
      Description: Build workshops frontend app
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
        EnvironmentVariables:
          - Name: PackageBucket
            Value:
              !ImportValue cloud-workshops-static-website-WebsiteBucketId
          - Name: CloudfrontId
            Value:
              !ImportValue cloud-workshops-static-website-CloudfrontId
      Source:
        Type: CODEPIPELINE
        BuildSpec: frontend/loan-offerer/buildspec.yaml
      TimeoutInMinutes: 10

  TestFrontendProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: TestWorkshopsFrontendApp
      Description: Test workshops frontend app
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
      Source:
        Type: CODEPIPELINE
        BuildSpec: frontend/loan-offerer/testspec.yaml
      TimeoutInMinutes: 10