  BackendCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: WorkshopsBackendApp
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactsBucket
      Stages:
        - Name: Source
          Actions:
            - Name: SourceCode
              Region: eu-central-1
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: '1'
                Provider: GitHub
              Configuration:
                Owner: wojciech-dabrowski
                Repo: ci-cd-cloud-workshops
                Branch: master
                OAuthToken: !Ref GithubToken
                PollForSourceChanges: true
              OutputArtifacts:
                - Name: SourceCode
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: BuildApp
              Region: eu-central-1
              InputArtifacts:
                - Name: SourceCode
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              Configuration:
                ProjectName: BuildWorkshopsBackendApp
              OutputArtifacts:
                - Name: TemplateOutput


  BuildBackendProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: BuildWorkshopsBackendApp
      Description: Build workshops backend app
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
        EnvironmentVariables:
          - Name: PackageBucket
            Value: !Ref ArtifactsBucket
          - Name: PackageBucketKey
            Value: WorkshopsBackendApp/CodePackage
      Source:
        Type: CODEPIPELINE
        BuildSpec: backend/buildspec.yaml
      TimeoutInMinutes: 10



  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: 
              - codebuild.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: "*"
              - Effect: Allow
                Action: "cloudfront:*"
                Resource: "*"
              - Effect: Allow
                Action: "logs:*"
                Resource: "*"