  BackendCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: WorkshopsBackendApp
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactsBucket
      Stages:
        - Name: Source
          Actions:
            - Name: SourceCode
              Region: eu-central-1
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: '1'
                Provider: GitHub
              Configuration:
                Owner: wojciech-dabrowski
                Repo: aws-ci-cd
                Branch: master
                OAuthToken: !Ref GithubToken
                PollForSourceChanges: true
              OutputArtifacts:
                - Name: SourceCode
              RunOrder: 1
            - Name: TemplateConfig
              Region: eu-central-1
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: S3
                Version: '1'
              Configuration:
                S3Bucket: !Ref ArtifactsBucket
                S3ObjectKey: WorkshopsBackendApp/template-config.zip
              OutputArtifacts:
                - Name: TemplateConfig
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: BuildApp
              Region: eu-central-1
              InputArtifacts:
                - Name: SourceCode
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              Configuration:
                ProjectName: BuildWorkshopsBackendApp
              OutputArtifacts:
                - Name: TemplateOutput
        - Name: Deploy
          Actions:
            - Name: CreateChangeSet
              InputArtifacts:
                - Name: TemplateOutput
                - Name: TemplateConfig
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: '1'
                Provider: CloudFormation
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                StackName: loan-offerer
                ChangeSetName: CodePipelineChangeSet
                TemplatePath: TemplateOutput::template-output.yaml
                TemplateConfiguration: TemplateConfig::template.config
                Capabilities: CAPABILITY_IAM
                RoleArn: !GetAtt CodePipelineRole.Arn
              RunOrder: 1
            - Name: DeployChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: '1'
                Provider: CloudFormation
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                StackName: loan-offerer
                ChangeSetName: CodePipelineChangeSet
              RunOrder: 2
