AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cope Pipeline for workshops app
Resources:
  ArtifactsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: workshops-app-cp-artifacts
      VersioningConfiguration:
        Status: Enabled
