version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - cd frontend/loan-offerer
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - ng build --outputHashing=all
  post_build:
    commands:
      - aws s3 sync dist/loan-offerer s3://${PackageBucket} --acl public-read --delete
      - aws cloudfront create-invalidation --distribution-id ${CloudfrontId} --paths "/*"
artifacts:
  files:
    - '**/*'
  base-directory: frontend/loan-offerer/dist
  discard-paths: yes